### ISSUE TITLE
Instalando o AddOn

### ISSUE THREAD

**Issue by ghost** [LigeroSmart/otrs.RocketChat#1]
O download do repositório para a instalação do AddOn não está funcionando. estão fazendo alguma manutenção? 

https://github.com/LigeroSmart/otrs.RocketChat#211-configura%C3%A7%C3%A3o-no-otrs

**Comment by richieri** [comment]
Olá @ghost, creio que esta issue foi resolvida há muito tempo. Vou encerrar esta issue. Obrigado!
