### ISSUE TITLE
Erro na criação do ticket de teste na integração com o OTRS

### ISSUE THREAD

**Issue by DjalmaCarvalho** [LigeroSmart/otrs.RocketChat#2]
Depois da integração realizada, ao colocar no webhook do livechat o endereço do webservice do OTRS no Rocket.Chat e clicar no "Enviar teste".  Dá o erro abaixo:
![webhook_rocketchat](https://user-images.githubusercontent.com/50991625/58329527-2874e400-7e0b-11e9-8c7e-56b997ea3919.jpg)

O erro só é capturado pelo apache, conforme abaixo:
![erroapache_rocketchat](https://user-images.githubusercontent.com/50991625/58329853-f2842f80-7e0b-11e9-8e80-51aa99da117f.jpg)

Ao analisar a API do OTRS 6 notei que houve mudanças e o pacote que faz a criação e as alterações nos artigos é o Kernel::System::Ticket::Article::Backend; Conforme o endereço da documentação: https://doc.otrs.com/doc/api/otrs/6.0/Perl/Kernel/System/Ticket/Article/Backend/Chat.pm.html ou https://doc.otrs.com/doc/api/otrs/6.0/Perl/Kernel/System/Ticket/Article/Backend/Email.pm.html

[IncomingChat.txt](https://github.com/LigeroSmart/otrs.RocketChat/files/3218168/IncomingChat.txt)

Desde já agradeço,

**Comment by richieri** [comment]
Olá @DjalmaCarvalho , já fizemos a correção! Obrigado!

**Comment by ghost** [comment]
Fazendo a instalação via repositório já vem com a correção?
