### ISSUE TITLE
Addon OTRS

### ISSUE THREAD

**Issue by L1n0r** [LigeroSmart/otrs.RocketChat#3]
Não esta sendo possível instalar o addon no OTRS. 
Aparece um erro informando que o addon não existe.

![erro-addon](https://user-images.githubusercontent.com/39285362/59553419-11896380-8f6b-11e9-88ba-5c5eb0213c1e.png)

**Comment by richieri** [comment]
Olá @ronil21 ,

Procurei por RelevantStates no nosso código e não encontrei nada. Pode dar mais detalhes do erro?

**Comment by L1n0r** [comment]
Olá,

@richieri onde posso obter mais logs para passar? Estou apenas tentando instalar o Addon e é exibido esse erro.
Obrigado.

**Comment by richieri** [comment]
@ronil21 , tenta mandar esse texto do print pra gente. Ele está cortado. Me manda a lista de outros addons que vc tem instalado aí tb com suas versões se possível

**Comment by richieri** [comment]
Vc está tentando instalar pelo repositório Ligero/Complemento?

**Comment by L1n0r** [comment]
@richieri vou montar o lab novamente. Como havia dado esse erro na vez que tentei (junho/2019) acabei deixando de lado.
Se der algum problema novamente, posto aqui.
Obrigado.

**Comment by richieri** [comment]
beleza @ronil21 , por ora então vou fechar essa issue. Assim que vc conseguir retestar, posta pra gente por favor se de erro novamente!
