### ISSUE TITLE
Instalação incompleta

### ISSUE THREAD

**Issue by diegoromal** [LigeroSmart/otrs.RocketChat#9]
Os arquivos não estão sendo inseridos nas devidas pastas após a instalação do pacote pelo otrs 6. Além disso, o WebService não está disponível para importação.
Seria isso mesmo?

**Comment by richieri** [comment]
@diegoromanio , qual versão do pacote?  
  
Seguiu por essa documentação?  
https://docs.ligerosmart.org/kb/como-integrar-rocket-chat-com-ligerosmart

**Comment by diegoromal** [comment]
É a ultima versão 6.0.5. Segui essa doc sim, e tentei em duas instalações diferentes, em ambos os casos ele não adicionou os arquivos nas pastas e não criou o webservice. A versão do otrs é 6.0.30.

**Comment by richieri** [comment]
Ah, então, a gente testou com o LigeroSmart, que tem alguns pacotes a mais. Você consegue dizer quais arquivos tá dando erro? Pode anexar um print aqui?

**Comment by diegoromal** [comment]
Pois é. Ele não inseriu nenhum na instalação do pacote, ai eu inseri manualmente, conforme o print. Porém o meu maior problema é ele não criar o webservice, tem em algum lugar o yaml dele para importar?

![image](https://user-images.githubusercontent.com/13037189/107815523-44908580-6d52-11eb-90be-5071744ebc1b.png)

**Comment by richieri** [comment]
@diegoromanio, me parece que é um erro de permissionamento no seu OTRS. Experimente rodar um otrs.SetPermissions.pl Conhece esse comando do OTRS?

Se for uma ambiente de homologação, manda um "chmod 777 /opt/otrs -R" pra testar

**Comment by diegoromal** [comment]
Eu já tinha aplicado permissão antes de instalar, mesmo assim não deu certo, em dois ambientes diferentes.
Esse print é depois de eu colocar os arquivos nas pastas específicas, antes disso ele acusa sem o arquivo.

**Comment by richieri** [comment]
Por favor, tente instalar pela linha de comando no servidor OTRS com o comando abaixo:

 bin/otrs.Console.pl Admin::Package::Install --force /localOndeVoceSalvouOAddon/Addonxxxxxx.opm

Muda ali o /localOndeVoceSalvouOAddon/Addonxxxxxx.opm pelo endereço do opm da integração.

Cola o resultado todo aqui pra gente por favor.

**Comment by diegoromal** [comment]
Eu joguei a saída do comando no arquivo em anexo.
[rocketchat-install.log](https://github.com/LigeroSmart/otrs.RocketChat/files/5974282/rocketchat-install.log)

**Comment by diegoromal** [comment]
Ele fica igual quando eu instalei pela interface:
![image](https://user-images.githubusercontent.com/13037189/107823085-ecf81700-6d5d-11eb-91ca-4262ea049729.png)

**Comment by richieri** [comment]
Que estranho! Por favor, anexa aqui o opm que você está tentando instalar. Exatamente o arquivo que você usou nas duas instâncias.

**Comment by richieri** [comment]
Será que você não está tentando instalar o ".sopm" ao invés do ".opm"? Isso explicaria o tal erro "Content not defined in File!"

**Comment by diegoromal** [comment]
Tem razão, é isso mesmo. O arquivo .opm não está junto aqui no github?

**Comment by richieri** [comment]
Fica em Releases: (mandei um print do meu celular)

![IMG_20210213_095222](https://user-images.githubusercontent.com/2002125/107850498-a2b87980-6de1-11eb-9f7c-fa79dc4d207f.jpg)

Me diga se deu certo por favor :)

**Comment by richieri** [comment]
O sopm é o arquivo que gera o opm :)
